### ISSUE TITLE
레이저빔 만들기

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2015/VesselDefense#4]
훌륭하고 아름다운 모양의 레이저빔을 생성한다

**Comment by NakOh** [comment]
Laser는 2개로 나뉘어져서 발사함(발사체가 2개임)

1개씩 조종 가능하며, 가운데 첨탑으로 레이저가 발사될 시 일정 에너지를 충전하여 강력한 대미지의 레이저를 한 방향으로 발사 할 수 있다. 

충전 속도는 레이저1개로 충전하냐, 2개로 충전하냐에 따라 달라진다. 

100%되는 순간 발사되며, 충전이 되고 있지 않으면 일정 시간 경과후 충전된 에너지가 소멸된다. 

기본적인 대미지가 매우 구리기 때문에 적절하게 사용하는 것이 좋을 듯 

왼쪽 오른쪽 레이저의 사각지대가 있기 때문에 사용자는 적절하게 돌아가면서 사용할 필요가 있다.
